version: '3.8'
services:
  rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    command: "tail -f /dev/null"
    volumes:
      - ./code:/app
      - ./cache:/cache
      - ./data:/data
    networks:
      - rag-network
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - rag-network 

networks:
  rag-network:
    external: false
  